import { toPng } from 'html-to-image'
import { jsPDF } from 'jspdf'
import { TeamRanking } from '@/types'
import { TeamRankingWithDelta } from '@/hooks/useSimulator'

export async function exportAsImage(elementId: string): Promise<void> {
  const element = document.getElementById(elementId)
  if (!element) {
    throw new Error('Element not found')
  }

  const dataUrl = await toPng(element, {
    backgroundColor: '#ffffff',
    pixelRatio: 2,
  })

  const link = document.createElement('a')
  link.download = `asa-rankings-${new Date().toISOString().split('T')[0]}.png`
  link.href = dataUrl
  link.click()
}

export async function exportAsPDF(rankings: TeamRanking[]): Promise<void> {
  const pdf = new jsPDF()
  const pageWidth = pdf.internal.pageSize.getWidth()
  const margin = 20
  let yPosition = 20

  // Title
  pdf.setFontSize(24)
  pdf.setFont('helvetica', 'bold')
  pdf.text('ASA ELO Simulator', pageWidth / 2, yPosition, { align: 'center' })
  yPosition += 10

  // Subtitle
  pdf.setFontSize(14)
  pdf.setFont('helvetica', 'normal')
  pdf.text('2026 Season Standings', pageWidth / 2, yPosition, { align: 'center' })
  yPosition += 8

  // Date
  pdf.setFontSize(10)
  pdf.setTextColor(100)
  pdf.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth / 2, yPosition, { align: 'center' })
  yPosition += 15

  // Horizontal line
  pdf.setDrawColor(218, 165, 32) // Gold color
  pdf.setLineWidth(1)
  pdf.line(margin, yPosition, pageWidth - margin, yPosition)
  yPosition += 10

  // Table headers
  pdf.setFontSize(11)
  pdf.setFont('helvetica', 'bold')
  pdf.setTextColor(0)
  pdf.text('Rank', margin, yPosition)
  pdf.text('Team', margin + 20, yPosition)
  pdf.text('ELO', pageWidth - margin - 30, yPosition)
  pdf.text('Change', pageWidth - margin, yPosition, { align: 'right' })
  yPosition += 8

  // Rankings
  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(10)

  rankings.forEach((team, idx) => {
    const isTop8 = idx < 8
    const ratingChange = team.rating - 1500

    // Highlight top 8
    if (isTop8) {
      pdf.setFillColor(240, 253, 244) // Light green
      pdf.rect(margin - 2, yPosition - 4, pageWidth - 2 * margin + 4, 7, 'F')
    }

    // Cutoff line at rank 8
    if (idx === 7) {
      pdf.setDrawColor(218, 165, 32)
      pdf.setLineWidth(0.5)
      pdf.line(margin, yPosition + 4, pageWidth - margin, yPosition + 4)
    }

    pdf.setTextColor(0)
    pdf.text(`${idx + 1}`, margin, yPosition)
    pdf.text(team.name, margin + 20, yPosition)
    pdf.text(team.rating.toFixed(2), pageWidth - margin - 30, yPosition)

    // Change color
    if (ratingChange > 0) {
      pdf.setTextColor(22, 163, 74) // Green
      pdf.text(`+${ratingChange.toFixed(2)}`, pageWidth - margin, yPosition, { align: 'right' })
    } else if (ratingChange < 0) {
      pdf.setTextColor(220, 38, 38) // Red
      pdf.text(ratingChange.toFixed(2), pageWidth - margin, yPosition, { align: 'right' })
    } else {
      pdf.setTextColor(100)
      pdf.text('0.00', pageWidth - margin, yPosition, { align: 'right' })
    }

    yPosition += 7

    // Check for page break
    if (yPosition > pdf.internal.pageSize.getHeight() - 30) {
      pdf.addPage()
      yPosition = 20
    }
  })

  // Footer
  yPosition += 10
  pdf.setFontSize(8)
  pdf.setTextColor(100)
  pdf.text('Generated by ASA ELO Simulator', pageWidth / 2, pdf.internal.pageSize.getHeight() - 10, { align: 'center' })

  pdf.save(`asa-rankings-${new Date().toISOString().split('T')[0]}.pdf`)
}

export async function copyToClipboard(rankings: TeamRanking[]): Promise<void> {
  const lines: string[] = [
    'ASA ELO Simulator - 2026 Season Standings',
    `Generated: ${new Date().toLocaleDateString()}`,
    '',
    'Rank | Team | ELO | Change',
    '-----------------------------------',
  ]

  rankings.forEach((team, idx) => {
    const ratingChange = team.rating - 1500
    const changeStr = ratingChange >= 0 ? `+${ratingChange.toFixed(2)}` : ratingChange.toFixed(2)
    const qualifier = idx < 8 ? ' *' : ''
    lines.push(`#${idx + 1}${qualifier} | ${team.name} | ${team.rating.toFixed(2)} | ${changeStr}`)
  })

  lines.push('')
  lines.push('* = Qualifying position for A3')
  lines.push('')
  lines.push('Generated by ASA ELO Simulator')

  await navigator.clipboard.writeText(lines.join('\n'))
}

export function exportToCSV(rankings: TeamRankingWithDelta[], getLastYearRating: (name: string) => number | null): void {
  const headers = ['Rank', 'Team', 'ELO Rating', 'Change', 'Delta', 'Original Rank']
  const rows = rankings.map(team => [
    team.rank,
    team.name,
    team.rating.toFixed(2),
    (team.rating - 1500 >= 0 ? '+' : '') + (team.rating - 1500).toFixed(2),
    team.delta > 0 ? `+${team.delta}` : team.delta,
    team.originalRank
  ])

  const csv = [headers, ...rows].map(row => row.join(',')).join('\n')
  const blob = new Blob([csv], { type: 'text/csv' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `asa-rankings-${new Date().toISOString().split('T')[0]}.csv`
  a.click()
  URL.revokeObjectURL(url)
}
